Assignment7/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment7.Controllers
{
    [Authorize]
    public class AlbumsController : Controller
    {
        // Reference to the manager object
        Manager m = new Manager();

        // GET: Albums
        public ActionResult Index()
        {
            return View(m.AlbumGetAll());
        }

        // GET: Albums/Details/5
        public ActionResult Details(int? id)
        {
            // Attempt to get the matching object
            var o = m.AlbumGetByIdWithDetail(id.GetValueOrDefault());

            if (o == null)
            {
                return HttpNotFound();
            }
            else
            {
                // Pass the object to the view
                return View(o);
            }
        }

        // Add new album method is actually located in the Artists controller

        // ############################################################
        // Add track for this album

        // GET: Albums/5/AddTrack
        [Route("albums/{id}/addtrack")]
        [Authorize(Roles = "Clerk")]
        public ActionResult AddTrack(int? id)
        {
            // Attempt to get the associated object
            var a = m.AlbumGetByIdWithDetail(id.GetValueOrDefault());

            if (a == null)
            {
                return HttpNotFound();
            }
            else
            {
                // Prepare the form
                var form = new TrackAddForm();

                // Attention 16 - Prepare the data for the add track form

                // Album name and identifier
                form.AlbumName = a.Name;
                form.AlbumId = a.Id;

                // Genre list
                form.GenreList = new SelectList(m.GenreGetAll(), dataValueField: "Name", dataTextField: "Name");

                // Attention 17 - Study the view code too

                return View(form);
            }
        }

        // POST: Albums/5/AddTrack
        [Route("albums/{id}/addtrack")]
        [Authorize(Roles = "Clerk")]
        [HttpPost]
        public ActionResult AddTrack(int? id, TrackAdd newItem)
        {
            // Validate the input
            if (!ModelState.IsValid & id.GetValueOrDefault() == newItem.AlbumId)
            {
                return RedirectToAction("details", "albums", new { id = id });
            }

            // Process the input
            var addedItem = m.TrackAdd(newItem);

            if (addedItem == null)
            {
                return RedirectToAction("details", "albums", new { id = id });
            }
            else
            {
                // Attention 19 - Must redirect to the tracks controller
                return RedirectToAction("details", "tracks", new { id = addedItem.Id });
            }
        }

    }
}

Assignment7/Controllers/TracksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment7.Controllers
{
    [Authorize]
    public class TracksController : Controller
    {
        // Reference to the manager object
        Manager m = new Manager();

        // GET: Tracks
        public ActionResult Index()
        {
            return View(m.TrackGetAll());
        }

        // GET: Tracks/Details/5
        public ActionResult Details(int? id)
        {
            // Attempt to get the matching object
            var o = m.TrackGetByIdWithDetail(id.GetValueOrDefault());

            if (o == null)
            {
                return HttpNotFound();
            }
            else
            {
                // Pass the object to the view
                return View(o);
            }
        }

        // Add new track method is actually located in the Artists controller

        // GET: Tracks/Edit/5
        [Authorize(Roles = "Coordinator")]
        public ActionResult Edit(int? id)
        {
            // Attention 21 - Track edit; study the view code too

            // Attempt to fetch the matching object
            var o = m.TrackGetByIdWithDetail(id.GetValueOrDefault());

            if (o == null)
            {
                return HttpNotFound();
            }
            else
            {
                // Create and configure an "edit form"

                var editForm = m.mapper.Map<TrackEditComposers>(o);

                return View(editForm);
            }
        }

        // POST: Tracks/Edit/5
        [HttpPost]
        [Authorize(Roles = "Coordinator")]
        public ActionResult Edit(int? id, TrackEditComposers newItem)
        {
            // Validate the input
            if (!ModelState.IsValid)
            {
                // Our "version 1" approach is to display the "edit form" again
                return RedirectToAction("edit", new { id = newItem.Id });
            }

            if (id.GetValueOrDefault() != newItem.Id)
            {
                // This appears to be data tampering, so redirect the user away
                return RedirectToAction("index");
            }

            // Attempt to do the update
            var editedItem = m.TrackEdit(newItem);

            if (editedItem == null)
            {
                // There was a problem updating the object
                // Our "version 1" approach is to display the "edit form" again
                return RedirectToAction("edit", new { id = newItem.Id });
            }
            else
            {
                // Show the details view, which will have the updated data
                return RedirectToAction("details", new { id = newItem.Id });
            }
        }

        // GET: Tracks/Delete/5
        [Authorize(Roles = "Coordinator")]
        public ActionResult Delete(int? id)
        {
            // Attention 26 - Track delete; study the view code too

            var itemToDelete = m.TrackGetByIdWithDetail(id.GetValueOrDefault());

            if (itemToDelete == null)
            {
                // Don't leak info about the delete attempt
                // Simply redirect
                return RedirectToAction("index");
            }
            else
            {
                return View(itemToDelete);
            }
        }

        // POST: Tracks/Delete/5
        [HttpPost]
        [Authorize(Roles = "Coordinator")]
        public ActionResult Delete(int? id, FormCollection collection)
        {
            var result = m.TrackDelete(id.GetValueOrDefault());

            // "result" will be true or false
            // We probably won't do much with the result, because 
            // we don't want to leak info about the delete attempt

            // In the end, we should just redirect to the list view
            return RedirectToAction("index");
        }



    }

}

Assignment7/Views/Tracks/Delete.cshtml
@model Assignment7.Controllers.TrackWithDetails

@{
    ViewBag.Title = "Delete";
}

<h2>Delete track @Model.Name</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Confirm with the Delete button, or go back</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Composers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Composers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Assignment7/Views/Tracks/Details.cshtml
@model Assignment7.Controllers.TrackWithDetails

@{
    ViewBag.Title = "Track details";
}

<h2>Details for track @Model.Name</h2>

<div>
    @*<h4>TrackWithDetails</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Composers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Composers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Clerk)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Clerk)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlbumsCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlbumsCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlbumNames)
        </dt>

        <dd>
            @foreach (var item in Model.AlbumNames)
            {
                <span>@item</span><br />
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AudioUrl)
        </dt>

        <dd>
            <audio src="/clip/@Model.Id" controls="controls"></audio> 
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("Back to list of tracks", "Index") |
    @Html.ActionLink("Back to list of albums", "Index", "Albums")
</p>

Assignment7/Views/Tracks/Edit.cshtml
@model Assignment7.Controllers.TrackEditComposers

@{
    ViewBag.Title = "Edit";
}

<h2>Edit track @Model.Name</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit the composer(s), and click the Save button</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Genre)

        <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @autofocus = "autofocus" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Composers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Composers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Composers, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assignment7/Views/Tracks/Index.cshtml
@model IEnumerable<Assignment7.Controllers.TrackBase>

@{
    ViewBag.Title = "List of tracks";
}

<h2>List of tracks</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Composers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.AlbumId)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Composers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.AlbumId)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>